/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 shape.gltf 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, OrthographicCamera } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/shape.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-1.404, 310.343, -1.299]}>
          <mesh geometry={nodes.Cube_2.geometry} material={nodes.Cube_2.material} position={[1.404, -2.422, 3.926]} rotation={[0.627, 0, Math.PI / 4]} />
        </group>
        <pointLight intensity={0.7} decay={2} distance={1127} color="#d287ff" position={[-612.918, 54.704, 750.468]} />
        <pointLight intensity={1} decay={2} distance={911} color="#ffaaaa" position={[775.129, 54.704, 226.875]} />
        <directionalLight intensity={0.5} decay={2} rotation={[0.747, 0.429, -1.149]} target={nodes.Directional_Light.target}>
          <primitive object={nodes.Directional_Light.target} position={[0, 0, -1]} />
        </directionalLight>
        <OrthographicCamera makeDefault={false} far={100000} near={0} position={[0, 0, 1000]} />
        <mesh geometry={nodes.Sphere_2.geometry} material={nodes.Sphere_2.material} position={[-619.065, 37.116, 744.518]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[773.635, 37.116, 239.864]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Rectangle.geometry} material={nodes.Rectangle.material} position={[-215.205, 0, -73.211]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/shape.gltf')
